### ISSUE TITLE
Planning unit data query

### ISSUE THREAD

**Issue by jeffreyhanson** [prioritizr/benchmark#1]
Does the `pu` column in the planning unit table (i.e `data/raw/planning-units/nplcc_cost_occupancy.zip`) contain values that correspond to the indices (cell numbers) of planning units in the planning unit raster data (i.e. `data/raw/planning-units/nplcc_planning_units.tif`)?

**Comment by ricschuster** [comment]
Correct, the `pu` column contains values that correspond to the indices of the planning unit raster data.

**Comment by jeffreyhanson** [comment]
Great - thanks!
